//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::puzzle::Entity as Puzzle;
pub use super::refresh_token::Entity as RefreshToken;
pub use super::solve::Entity as Solve;
pub use super::user::Entity as User;
