//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "puzzle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::solve::Entity")]
    Solve,
}

impl Related<super::solve::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Solve.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
