//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "solve")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
    pub owner_id: i32,
    #[sea_orm(column_type = "Double")]
    pub time: f64,
    pub scramble: Option<String>,
    pub puzzle_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::puzzle::Entity",
        from = "Column::PuzzleId",
        to = "super::puzzle::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Puzzle,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OwnerId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::puzzle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Puzzle.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
